### ISSUE TITLE
Users can to securely login to the web app

### ISSUE THREAD

**Issue by mtfuller** [ksu-svt/svt-event-web-app#1]

**Comment by vyarlagad** [comment]
just wrote a small basic login form and created an admin account, but I need access to push to remote

**Comment by mtfuller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SVT Event App - User Login](https://trello.com/c/rwoh07n3/19-svt-event-app-user-login)

**Comment by vyarlagad** [comment]
You ended up getting it fixed ?

**Comment by mtfuller** [comment]
Solved in #15
