### ISSUE TITLE
Users can see a list of all member data

### ISSUE THREAD

**Issue by mtfuller** [ksu-svt/svt-event-web-app#3]
Officers need to have a way to see a list of all members and how many events they have attended. How many are ME? How many are juniors or seniors? We need a way to easily display important member info that officers can see at a glance.

**Comment by mtfuller** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SVT Event App - Member List](https://trello.com/c/wb5XcuPP/21-svt-event-app-member-list)

**Comment by karimrattani** [comment]
which data do we need to show the user and to the officer?

**Comment by mtfuller** [comment]
For users, we need to only see upcoming events and member contact information. Officers should see everything users can see, but can see all user points, all events and event attendance information. Is that enough to get started, or do you think we should formally define the information that members see and the information that officers see.

**Comment by karimrattani** [comment]
I think we should get started with events and roaster, then we can expand it. We will probably need to add another model for member attendance

**Comment by mtfuller** [comment]
I think we can call this complete for now. We can create member/event detail pages later.
